apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      component: {{ .Values.component.value }}
  template:
    metadata:
      labels:
        component: {{ .Values.component.value }}
    spec:
      containers:
        - name: payment-service
          image: {{ .Values.image.repository }}/{{ .Values.image.name }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 9191
